# Generated by Django 3.2.8 on 2021-11-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211102_2126'),
        ('main_app', '0003_auto_20211102_2259'),
    ]

    operations = [
    ]
