# Generated by Django 3.1.2 on 2021-11-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211102_2259'),
        ('main_app', '0002_auto_20211102_2126'),
    ]

    operations = [
    ]
