# Generated by Django 3.2.8 on 2021-11-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_0002_auto_20211102_2126_0003_auto_20211102_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
