# Generated by Django 3.1.2 on 2021-11-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_event_date'),
        ('main_app', '0004_merge_20211102_2340'),
    ]

    operations = [
    ]
