# Generated by Django 3.2.8 on 2021-11-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png', max_length=600, null=True),
        ),
    ]
